CREATE TABLE users (
	user VARCHAR(256) PRIMARY KEY NOT NULL,
	pass VARCHAR(256) NOT NULL);

CREATE TABLE  followingTracker(
  userWhoFollows VARCHAR(256) NOT NULL,
  followedUser VARCHAR(256) NOT null);

CREATE TABLE posts(
  user VARCHAR(256) NOT NULL,
  post VARCHAR(256) NOT NULL,
  time DATETIME NOT NULL);

ALTER TABLE posts
ADD CONSTRAINT idx_user
FOREIGN KEY (user)
REFERENCES users (user)
ON DELETE CASCADE
ON UPDATE RESTRICT;


ALTER TABLE followingTracker
ADD CONSTRAINT idx_followerUser
FOREIGN KEY (userWhoFollows)
REFERENCES users (user)
ON DELETE CASCADE
ON UPDATE RESTRICT;


ALTER TABLE followingTracker
ADD CONSTRAINT idx_followedUser
FOREIGN KEY (followedUser)
REFERENCES users (user)
ON DELETE CASCADE
ON UPDATE RESTRICT;

CREATE TABLE DMs(
  sender VARCHAR(64) NOT NULL,
  receiver VARCHAR(64) NOT NULL,
  title VARCHAR(64),
  message TEXT NOT NULL,
  time DATETIME NOT NULL);

INSERT INTO DMs
    VALUE ('Nikola123', 'alokin','test poruka','Pozdrav alokin, to sam ja. Nikola123', now());

ALTER TABLE DMs
  ADD CONSTRAINT idx_msgSender
  FOREIGN KEY (sender)
  REFERENCES users (user)
  ON DELETE CASCADE
  ON UPDATE RESTRICT;

ALTER TABLE DMs
  ADD CONSTRAINT idx_msgReceiver
  FOREIGN KEY (receiver)
  REFERENCES users (user)
  ON DELETE CASCADE
  ON UPDATE RESTRICT;